# Generated by Django 3.2.6 on 2021-08-16 13:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='token',
            field=models.UUIDField(verbose_name=uuid.UUID('0a7a49e1-9c6d-46a8-90d5-8f266cb4596d')),
        ),
    ]
